insert into CabType (CabTypeName) values ('Ram 3500');
insert into CabType (CabTypeName) values ('CL-Class');
insert into CabType (CabTypeName) values ('Chariot');
insert into CabType (CabTypeName) values ('Ram 1500 Club');
insert into CabType (CabTypeName) values ('Firebird');
insert into CabType (CabTypeName) values ('Viper');
insert into CabType (CabTypeName) values ('Hombre Space');
insert into CabType (CabTypeName) values ('Town Car');
insert into CabType (CabTypeName) values ('Cooper Countryman');
insert into CabType (CabTypeName) values ('DB9');
insert into CabType (CabTypeName) values ('Carrera GT');
insert into CabType (CabTypeName) values ('Breeze');
insert into CabType (CabTypeName) values ('E-Series');
insert into CabType (CabTypeName) values ('Corolla');
insert into CabType (CabTypeName) values ('Stealth');
insert into CabType (CabTypeName) values ('Bronco');
insert into CabType (CabTypeName) values ('A6');
insert into CabType (CabTypeName) values ('911');
insert into CabType (CabTypeName) values ('960');
insert into CabType (CabTypeName) values ('Express 2500');
insert into CabType (CabTypeName) values ('Tacoma');
insert into CabType (CabTypeName) values ('CX-9');
insert into CabType (CabTypeName) values ('B2600');
insert into CabType (CabTypeName) values ('CL-Class');
insert into CabType (CabTypeName) values ('Cutlass Supreme');
insert into CabType (CabTypeName) values ('B-Series Plus');
insert into CabType (CabTypeName) values ('Accent');
insert into CabType (CabTypeName) values ('Range Rover');
insert into CabType (CabTypeName) values ('MKS');
insert into CabType (CabTypeName) values ('F430 Spider');
insert into CabType (CabTypeName) values ('GTI');
insert into CabType (CabTypeName) values ('Dakota');
insert into CabType (CabTypeName) values ('S60');
insert into CabType (CabTypeName) values ('Eclipse');
insert into CabType (CabTypeName) values ('Econoline E350');
insert into CabType (CabTypeName) values ('Fortwo');
insert into CabType (CabTypeName) values ('Range Rover Sport');
insert into CabType (CabTypeName) values ('Sunfire');
insert into CabType (CabTypeName) values ('5 Series');
insert into CabType (CabTypeName) values ('Corvette');
insert into CabType (CabTypeName) values ('G');
insert into CabType (CabTypeName) values ('Highlander');
insert into CabType (CabTypeName) values ('911');
insert into CabType (CabTypeName) values ('Express 2500');
insert into CabType (CabTypeName) values ('Stratus');
insert into CabType (CabTypeName) values ('Probe');
insert into CabType (CabTypeName) values ('Q7');
insert into CabType (CabTypeName) values ('Echo');
insert into CabType (CabTypeName) values ('Continental Flying Spur');
insert into CabType (CabTypeName) values ('Odyssey');
