insert into Place (PlaceName) values ('Yanwo');
insert into Place (PlaceName) values ('Triesenberg');
insert into Place (PlaceName) values ('Dordrecht');
insert into Place (PlaceName) values ('Ledoy');
insert into Place (PlaceName) values ('Cauto Cristo');
insert into Place (PlaceName) values ('Nanjie');
insert into Place (PlaceName) values ('Dongdu');
insert into Place (PlaceName) values ('Rancharia');
insert into Place (PlaceName) values ('Xiatang');
insert into Place (PlaceName) values ('Mueang Suang');
insert into Place (PlaceName) values ('Igcocolo');
insert into Place (PlaceName) values ('Tayuan');
insert into Place (PlaceName) values ('Kamárai');
insert into Place (PlaceName) values ('Muriaé');
insert into Place (PlaceName) values ('Jelat');
insert into Place (PlaceName) values ('Norfolk');
insert into Place (PlaceName) values ('Nanjia');
insert into Place (PlaceName) values ('Palma De Mallorca');
insert into Place (PlaceName) values ('Kisai');
insert into Place (PlaceName) values ('Saint Louis');
insert into Place (PlaceName) values ('Chikan');
insert into Place (PlaceName) values ('Hongsipu');
insert into Place (PlaceName) values ('Kalilangan');
insert into Place (PlaceName) values ('E’erdun Wula');
insert into Place (PlaceName) values ('Nanyang');
insert into Place (PlaceName) values ('Šilheřovice');
insert into Place (PlaceName) values ('Makoko');
insert into Place (PlaceName) values ('Dula’er Ewenke Minzu');
insert into Place (PlaceName) values ('San Miguel');
insert into Place (PlaceName) values ('Souto do Meio');
insert into Place (PlaceName) values ('Yinjiang');
insert into Place (PlaceName) values ('Skrzyszów');
insert into Place (PlaceName) values ('Naka');
insert into Place (PlaceName) values ('Liping');
insert into Place (PlaceName) values ('Pinheiros');
insert into Place (PlaceName) values ('Lijia');
insert into Place (PlaceName) values ('Färgelanda');
insert into Place (PlaceName) values ('Chalon-sur-Saône');
insert into Place (PlaceName) values ('Debre Werk’');
insert into Place (PlaceName) values ('Berezovo');
insert into Place (PlaceName) values ('Jinsheng');
insert into Place (PlaceName) values ('Pagatan');
insert into Place (PlaceName) values ('San Ramon');
insert into Place (PlaceName) values ('Conima');
insert into Place (PlaceName) values ('Mstsislaw');
insert into Place (PlaceName) values ('Boudinar');
insert into Place (PlaceName) values ('Taizhou');
insert into Place (PlaceName) values ('Staryy Merchyk');
insert into Place (PlaceName) values ('Henghe');
insert into Place (PlaceName) values ('Providencia');
